### ISSUE TITLE
Cool library, couple questions re: mypy, derived classes

### ISSUE THREAD

**Issue by jgarvin** [curegit/reification#7]
- mypy doesn't support the new `MyClass[T]` syntax yet, but once it does will whatever metaprogramming shenanigans going on here still work? will it's flow typing understand the `isinstance` checking? e.g. if I do `if isinstance(x, ReifiedStack[int])`, will it understand within the branch that it's specifically a `ReifiedStack[int]` and not just `ReifiedStack`?

- If you have a long inheritance hierarchy but where the base class inherits `Reified`, will it work for everything generic in the hierarchy, or does it need to be mixed in multiple times? i.e. does it work for all 3 of these classes `class Base(Reified)`, `class Derived1[A, B](Base)`, `class Derived2[C](Derived1)`  ?

**Comment by curegit** [comment]
Thanks for showing an interest in my work.

## 1. Support for `isinstance` flow checks

Whether isinstance(x, ReifiedStack[int]) will be valid depends on future support from mypy.

However, using them for static flow analysis could be challenging.
Because `isinstance` doesn't accept `GenericAlias` but type bracket substitution by `__class_getitem__` should return `GenericAlias` according to the Python's typing documentation. (The current implementation of the Reified class uses the __class_getitem__ method that returns actual types.)

https://docs.python.org/3/reference/datamodel.html#class-getitem-versus-getitem

## 2. Nested Reified

In long inheritance hierarchies where the base class inherits from Reified, the functionality **will work for all unless** `__class_getitem__` is overridden by another mixin.

So your examples are OK:

```py
class Base(Reified):
    pass

class Derived1[A, B](Base):
    pass

class Derived2[C](Derived1): # Derived1[C, C] is also OK
    pass

print(Derived2[int].targ) # int
```

This is because typing.Generic's place in the MRO becomes last.

```py
[<class 'types.Derived2'>, <class '__main__.Derived2'>, <class 'types.Derived1'>, <class '__main__.Derived1'>, <class '__main__.Base'>, <class 'reification.abs.Reified'>, <class 'typing.Generic'>, <class 'object'>]
```

In contrast, classes having special `__class_getitem__` like list[T], ndarray[T] are problematic edge cases.

```py
class Derived2[C](list[C], Derived1[C, C]):
    pass

print(Derived2[int].targ) # (C, C)

# (C, C) is from Derived1[C, C]
# [int] is trapped by list class

# MRO
#[<class '__main__.Derived2'>, <class 'list'>, <class 'types.Derived1'>, <class '__main__.Derived1'>, <class '__main__.Base'>, <class 'reification.abs.Reified'>, <class 'typing.Generic'>, <class 'object'>]
```

A workaround for that is like:

```py
# Now Reified is prior to list[C]
class RList[C](Reified, list[C]):
    pass

# Note that Derived2[C](Reified, list[C], Derived1[C, C]) fails resolving MRO
class Derived2[C](RList[C], Derived1[C, C]):
    pass

print(Derived2[int].targ) # int
```
